### ISSUE TITLE
访客人数统计问题

### ISSUE THREAD

**Issue by codeKingPub** [88250/solo-blog#2]
局域网获取的ip地址好像不对，会统计出好几个人，但实际只有一个ip访问。
![image](https://user-images.githubusercontent.com/58844317/70787846-90504380-1dca-11ea-9f6f-308e3a3161bc.png)
![image](https://user-images.githubusercontent.com/58844317/70787881-a3631380-1dca-11ea-8754-128777ffc654.png)

**Comment by 88250** [comment]
IP 不一样就认为是不同的访客了。
